### ISSUE TITLE
Possibility to modify R2D2 implementation for vector-based observations

### ISSUE THREAD

**Issue by hai-h-nguyen** [twni2016/self-predictive-rl#1]
Hi,

What do you think about the possibility above? Will it be hard to do so? Thank you!

**Comment by twni2016** [comment]
Hi,

Our experiments indeed use vector-based observations. We use the symbolic observation $7\times 7 \times 3$ and flatten it to $147$-dim vector [here](https://github.com/twni2016/self-predictive-rl/blob/main/minigrid_code/run.py#L94). 

You can check appendix E.3 for details.
